Args = --initialize-at-build-time=kotlin \
       --initialize-at-build-time=kotlinx.coroutines \
       --initialize-at-build-time=io.ktor \
       --initialize-at-build-time=kotlinx.serialization \
       --enable-url-protocols=http,https \
       -H:+InstallExitHandlers
